# Generated by Django 4.0.3 on 2022-03-31 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gas', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('water', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('internet', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('mobile', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('clothes', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('other', models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('freq_rent', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_elec', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_gas', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_water', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_internet', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_mobile', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_transport', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_food', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_clothes', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
                ('freq_other', models.DecimalField(choices=[(30, 'Monthly'), (14, 'Fortnightly'), (7, 'Weekly')], decimal_places=2, default=30, max_digits=20, max_length=3, verbose_name='')),
            ],
        ),
    ]
